name: Go Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Install dependencies
        run: go mod download

      - name: Install test dependencies
        run: |
          go get github.com/lib/pq
          go get github.com/stretchr/testify/require
          go mod tidy

      - name: Install SQLC
        run: |
          go install github.com/kyleconroy/sqlc/cmd/sqlc@latest

      - name: Build (release mode)
        run: |
          mkdir -p bin
          go build -ldflags="-s -w" -trimpath -o bin/app .

      - name: Test
        run: go test -v ./...